framework:
    router:
        utf8: true

        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        #default_uri: http://localhost

when@prod:
    framework:
        router:
            strict_requirements: null


#home_list:
#    path: /home
#    # the controller value has the format 'controller_class::method_name'
#    controller: App\Controller\HomeController::list

# Create route for scheduler in your app
#calendar:
#    resource: "@App/src/CalendarController.php"
#        prefix: /